### Problem 4: Matrix Transpose and Inverse

In [4]:
import numpy as np
np.set_printoptions(precision=3, suppress=True)

np.random.seed(0)

# Creating 3 random 3 x 3 matrices with integers from -10 to 10
A1 = np.random.randint(-10, 11, (3, 3))
A2 = np.random.randint(-10, 11, (3, 3))
A3 = np.random.randint(-10, 11, (3, 3))

# Printing the matrices
print("Matrix A1:\n", A1)
print("\nMatrix A2:\n", A2)
print("\nMatrix A3:\n", A3)

Matrix A1:
 [[  2   5 -10]
 [ -7  -7  -3]
 [ -1   9   8]]

Matrix A2:
 [[-6 -4  2]
 [-9 -4 -3]
 [ 4  7 -5]]

Matrix A3:
 [[ 3 -2 -1]
 [10  9  6]
 [ 9 -5  5]]


In [10]:
matrices = [A1, A2, A3]
inverse_matrices = []

# Looping through each matrix
for i, A in enumerate(matrices, start=1):

    # Computing the determinant to check if the inverse exists
    if abs(np.linalg.det(A)) < 1e-9:
        print("Inverse does not exist")
        inverse_matrices.append(None)
        continue

    # Compute the inverse using NumPy
    A_inv = np.linalg.inv(A)
    inverse_matrices.append(A_inv)
    print(f"Inverse Matrix A{i}:")
    print(A_inv)

Inverse Matrix A1:
[[-0.031 -0.139 -0.091]
 [ 0.063  0.006  0.081]
 [-0.075 -0.025  0.022]]
Inverse Matrix A2:
[[-0.366  0.054 -0.179]
 [ 0.509 -0.196  0.321]
 [ 0.42  -0.232  0.107]]
Inverse Matrix A3:
[[ 0.216  0.043 -0.009]
 [ 0.011  0.069 -0.08 ]
 [-0.376 -0.009  0.135]]


In [13]:
for i in range(len(matrices)):

    A = matrices[i]
    A_inv = inverse_matrices[i]

    if A_inv is None:
        print(f"A{i+1} has no inverse, cannot compute product.\n")
        continue

    product = A @ A_inv
    
    print(f"Identity Matrix A{i+1}:")
    print(np.abs(product))

Identity Matrix A1:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Identity Matrix A2:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Identity Matrix A3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
